name: action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Maven test
        run: mvn test -B -Dio.netty.leakDetection.level=PARANOID
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}